name: doctest-key4hep

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        RELEASE: ['/cvmfs/sw-nightlies.hsf.org/key4hep']
        PAGE: ['doc/starterkit/k4SimDelphes/Readme.md']
    steps:
      - uses: actions/checkout@v3
      - uses: cvmfs-contrib/github-action-cvmfs@v3
      - uses: aidasoft/run-lcg-view@v4
        with:
          container: centos7
          view-path: ${{ matrix.RELEASE }}
          run: |
            mkdir testdir
            cat .github/scripts/yamlheader.md ${{ matrix.PAGE }} > testdir/test.md
            cd testdir
            jupytext test.md -o test.ipynb --execute
