name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: aidasoft/run-lcg-view@v4
      with:
        release-platform: LCG_102/x86_64-centos7-clang12-opt
        run: |
          echo "::group::Setup pre-commit"
          export PYTHONPATH=$(python -m site --user-site):$PYTHONPATH
          export PATH=/root/.local/bin:$PATH
          pip install pre-commit
          # Use virtualenv from the LCG release
          pip uninstall --yes virtualenv
          echo "::endgroup::"
          echo "::group::Run pre-commit"
          pre-commit run --show-diff-on-failure \
            --color=always \
            --all-files
          echo "::endgroup::"
